apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1acp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-1acp@sha256:1d7bb560d83c0224cdb35ff60522691f3f9ed3ffe42fb1ae9c7fe5cb6bf5f870
        name: my-nodejs
        resources: {}
status: {}
